### ISSUE TITLE
next steps

### ISSUE THREAD

**Issue by fraguada** [ztepler/hic-contract-proxy#1]
We're discussing this capability here: https://github.com/hicetnunc2000/hicetnunc/issues/586

What would be the next steps to make this functionality useful as an mvp to enable collaborative OBJKTS?

**Comment by ztepler** [comment]
I am feeling stupid for not seeing issues on github. Sorry, I am still studying how this opensource communication works.
Just read this feature request in hicetnunc issues, thank you for mention and support.
There was a lot of work that have been done in the contract side and UI side, the thing is working.
Next steps is to make proper documentation for the contract side and resolve indexer issues to perform UI merge.

**Comment by fraguada** [comment]
@ztepler I've been following on twitter and on discord. The work you and the team have done is really exciting!
